### ISSUE TITLE
Bug: rescope_before_pick crashes with TypeError on _after_applies kwarg (regression from PR #1938)

### ISSUE THREAD

**Issue by FidoCanCode** [FidoCanCode/home#1955]
## Observed

Fido enters a crash loop on every worker tick:

\`\`\`
TypeError: reorder_tasks() got an unexpected keyword argument '_after_applies'
  File \"src/fido/worker.py\", line 5276, in rescope_before_pick
    self._reorder_tasks_fn(self._tasks, commit_summary, reorder_kwargs)
  File \"src/fido/worker.py\", line 5300, in _reorder_tasks_fn
    self._task_reorderer(tasks_obj, commit_summary, **reorder_kwargs)
\`\`\`

In production this manifested as \`crashes 154\` over ~1.5h on FidoCanCode/home, blocking PR #1951 work.

## Root cause

Regression from PR #1938 (codex fourteenth-round P2 fix in commit 4808ae3). \`Dispatcher._make_reorder_kwargs\` now stores a mutable \`_after_applies\` list in the returned kwargs so the coalesce branch can extend it.

That key is a SIDE-CHANNEL captured by \`on_done\`'s closure and must NOT reach \`reorder_tasks()\`. \`reorder_tasks_background\` (events.py:3520) correctly filters it out before the call, but \`Worker.rescope_before_pick\` consumes the same kwargs dict via \`_task_reorderer\` and does not.

## Fix

Strip \`_after_applies\` at the boundary in \`Worker._reorder_tasks_fn\` (worker.py:5297-5300), matching the pattern already in \`reorder_tasks_background\`. Better yet: centralize the side-channel key + the strip into a small helper so a future call site can't repeat this oversight.

## Regression test

A test that calls \`Worker.rescope_before_pick\` with a real \`_make_reorder_kwargs\`-built dict (not a stub) and asserts no TypeError reaches the reorder call.

Source: PR #1938 commit 4808ae3, error at worker.py:5300.
